export const nodeConfigs = {
  input: {
    type: 'input',
    icon: '📥',
    label: 'Input',
    inputs: [],
    outputs: ['output'],
    showInput: true,
    placeholder: 'Enter input data...',
    description: 'Data input node',
  },
  output: {
    type: 'output',
    icon: '📤',
    label: 'Output',
    inputs: ['input'],
    outputs: [],
    showInput: false,
    description: 'Final output node',
  },
  llm: {
    type: 'llm',
    icon: '🤖',
    label: 'LLM',
    inputs: ['prompt', 'context'],
    outputs: ['response'],
    showInput: true,
    placeholder: 'Configure LLM settings...',
    description: 'Language model processor',
  },
  text: {
    type: 'text',
    icon: '📝',
    label: 'Text',
    inputs: ['input'],
    outputs: ['output'],
    showInput: true,
    placeholder: 'Enter text... Use {{variable}} for dynamic inputs',
    description: 'Text processing node',
  },
  transformer: {
    type: 'transformer',
    icon: '🔄',
    label: 'Transformer',
    inputs: ['input', 'config'],
    outputs: ['output', 'metadata'],
    showInput: true,
    placeholder: 'Transform data...',
    description: 'Data transformation',
  },
  api: {
    type: 'api',
    icon: '🌐',
    label: 'API Call',
    inputs: ['url', 'params'],
    outputs: ['response', 'error'],
    showInput: true,
    placeholder: 'API endpoint...',
    description: 'External API integration',
  },
  database: {
    type: 'database',
    icon: '💾',
    label: 'Database',
    inputs: ['query', 'connection'],
    outputs: ['result'],
    showInput: true,
    placeholder: 'SQL query...',
    description: 'Database operations',
  },
  validator: {
    type: 'validator',
    icon: '✓',
    label: 'Validator',
    inputs: ['data', 'schema'],
    outputs: ['valid', 'invalid'],
    showInput: true,
    placeholder: 'Validation rules...',
    description: 'Data validation',
  },
  filter: {
    type: 'filter',
    icon: '🔍',
    label: 'Filter',
    inputs: ['data', 'criteria'],
    outputs: ['filtered'],
    showInput: true,
    placeholder: 'Filter conditions...',
    description: 'Filter data streams',
  },
};